version: "3.8"

services:
  web:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    command: >
      bash -c "chown -R www-data:www-data /var/www/html && apache2-foreground"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db:
